language: node_js
node_js:
  - '8'

addons:
  ssh_known_hosts:
    - deploy@104.248.18.71
    - deploy@iot.itprof.sk

script: npm run prestart:deploy

after_success:
  - openssl aes-256-cbc -K $encrypted_a713e34b192a_key -iv $encrypted_a713e34b192a_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa

before_install:
  - sudo apt-get install -y build-essential python
  - npm install -g node-gyp node-pre-gyp

deploy:
  provider: script
  skip_cleanup: true
  script: bash deploy.sh
  on:
    branch: dev
